version: '2'

services:
  drone-server:
    image: drone/drone:1.0.0
    ports:
      - 8082:80
    volumes:
      - ./:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      - DRONE_SERVER_HOST=${DRONE_SERVER_HOST}
      - DRONE_SERVER_PROTO=${DRONE_SERVER_PROTO}
      - DRONE_TLS_AUTOCERT=false
      - DRONE_RUNNER_CAPACITY=3
      # GitHub Config
      - DRONE_GITHUB_SERVER=https://github.com
      - DRONE_GITHUB_CLIENT_ID=ccf51708f5d3bf22009f
      - DRONE_GITHUB_CLIENT_SECRET=18f79a52f02762a7dd3207140908885d09348966
      - DRONE_LOGS_PRETTY=true
      - DRONE_LOGS_COLOR=true